### ISSUE TITLE
Weird handling of a pipe

### ISSUE THREAD

**Issue by Naereen** [moskytw/git-count#5]
For instance:
```bash
$ git-count -a lbesson -p y | head -n1
2018-01-01      77
Traceback (most recent call last):
  File "git-count", line 142, in <module>
    main()
  File "git-count", line 131, in main
    clime.start({'count': count})
  File "/usr/local/lib/python2.7/dist-packages/clime/core.py", line 693, in start
    prog.main()
  File "/usr/local/lib/python2.7/dist-packages/clime/core.py", line 614, in main
    self.complain(e)
  File "/usr/local/lib/python2.7/dist-packages/clime/core.py", line 562, in complain
    print('%s: %s' % (self.name, msg), file=sys.stdout)
IOError: [Errno 32] Broken pipe
```

**Comment by Naereen** [comment]
The issue comes from clime, I will open an issue there
